export NODE_ENV=production
export DBNAME=kasapburada
export PORT=3005
export DBADDRESS=ec2-18-237-6-120.us-west-2.compute.amazonaws.com
export DBUSER=kasapuser
export DBPWD=cGgyMDE4Li4=
export DBPORT=3306
export EMAILHOST=mail.kasaptanal.com
export EMAILPORT=8889
export EMAILUSERNAME=noreply@kasaptanal.com
export EMAILPASS=Deneme987@.